Atividade unit test
cesar-school/eta-unit-testing-project-2019.1-Manaus pull request #4
Opened 2020-08-21 23:25 UTC by Mistercleng

2020-10-27 06:47 UTC, miltonmc requested changes

2020-10-27 06:47 UTC, miltonmc commented on src/main/java/school/cesar/eta/unit/Person.java
> +    public LocalDate getNow() { return LocalDate.now();}
O código da aplicação  não deveria ter sido alterado

2020-10-27 06:47 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        assertTrue(name == "Jon" && lastname == "Snow");
O método que deveria ter sido testado segundo descrito no teste deveria ter sido `getName()`

2020-10-27 06:47 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        assertTrue(name == "Jon");
O método que deveria ter sido testado segundo descrito no teste deveria ter sido `getName()`

2020-10-27 06:47 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        assertTrue(lastname == "Snow");
O método que deveria ter sido testado segundo descrito no teste deveria ter sido `getName()`

2020-10-27 06:47 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +            Integer.parseInt("Name must be filled");
O método que deveria ter sido testado segundo descrito no teste deveria ter sido `getName()`

2020-10-27 06:47 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        LocalDate date =LocalDate.now();
O método `getNow()` está utilizando a data que é uma variável de ambiente, e variável de ambiente devem ser isoladas para não causar intermitências nos resultados dos testes. Nessa caso, uma opção seria utilizar um stub do método `getNow()`.

2020-10-27 06:47 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        LocalDate date =LocalDate.now();
O método `getNow()` está utilizando a data que é uma variável de ambiente, e variável de ambiente devem ser isoladas para não causar intermitências nos resultados dos testes. Nessa caso, uma opção seria utilizar um stub do método `getNow()`.

2020-10-27 06:47 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        LocalDate date =LocalDate.now();
O método `getNow()` está utilizando a data que é uma variável de ambiente, e variável de ambiente devem ser isoladas para não causar intermitências nos resultados dos testes. Nessa caso, uma opção seria utilizar um stub do método `getNow()`.

2020-10-27 06:47 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        boolean family = person.isFamily(relative);
Esta chamada acopla o sucesso do teste a correta implementação `isFamily()`. Testes unitários devem isolar o cenário que está sendo testado.

2020-10-27 06:47 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        assertTrue(person.isFamily(familyUpdate)&&familyUpdate.isFamily(person));
- Se atenha ao cenário especificado no teste
- Esta chamada acopla o sucesso do teste a correta implementação `isFamily()`. Testes unitários devem isolar o cenário que está sendo testado.

2020-10-27 06:47 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        familyUpdate.addToFamily(person);
- Se atenha ao cenário especificado no teste

2020-10-27 06:47 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        person.addToFamily(person);
Esta chamada acopla o sucesso do teste a correta implementação `addToFamily()`. Testes unitários devem isolar o cenário que está sendo testado.

2020-11-02 02:53 UTC, Mistercleng commented on src/main/java/school/cesar/eta/unit/Person.java
> +    public LocalDate getNow() { return LocalDate.now();}
Na realidade foi a IDE que ajustou, o método nem modificou em nada.

2020-11-02 02:53 UTC, Mistercleng commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +            Integer.parseInt("Name must be filled");
Reajustado para getName() e adiconado o uso do mockito

2020-11-08 00:18 UTC, Mistercleng commented
Correções aplicadas

2020-11-11 06:11 UTC, miltonmc approved these changes
Aprovado!

2020-12-17 11:45 UTC, closed without merging